### ISSUE TITLE
Cannot download and access articles

### ISSUE THREAD

**Issue by LucasJavaudin** [LucasJavaudin/MetropolisWebInterface#10]
The pdfs are correctly stored in the _articles/_ directory but I cannot download or access them.
If I am clicking on the link to the pdf, I get an error 404. It seems that the pdf are stored in _./articles/_ but the website is looking for them at _./website_files/articles_.

**Comment by syrix78** [comment]
I think the issue is that I have set a MEDIA_URL inside settings.py and forgot to mention it. 
Try adding this to ./metropolis_web_interface/settings.py:
`MEDIA_URL = '/website_files/'`
`MEDIA_ROOT = BASE_DIR + '/website_files/'`
