### ISSUE TITLE
Cannot extract exported zip

### ISSUE THREAD

**Issue by LucasJavaudin** [LucasJavaudin/MetropolisWebInterface#11]
I successfully downloaded a zip of a simulation but I cannot extract all files from the zip file. I can however extract the file one by one. If I try to extract all, I get an error _(Circular.zip exists but is not directory)_. I tested it on Linux and Windows. Probably, removing the `.zip` in the name of the directory inside the zip file would solve the problem.

**Comment by syrix78** [comment]
Should be fixed with commit [5fcbc57](https://github.com/LucasJavaudin/MetropolisWebInterface/commit/5fcbc57bb778a1846b265a4fb76f152be942bdcb)
