### ISSUE TITLE
Cannot save the results (the simulator keeps saving them)

### ISSUE THREAD

**Issue by saulbh** [LucasJavaudin/MetropolisWebInterface#14]
I tried to run a simple simulation, which I ran previously, but it seems that the simulator cannot save the results. The log file stops at "saving results..." and keeps running for a long time (never finishes). Is the internal server working well? I ran the first simulation in the Netherlands, I am now in Mexico and cannot run it.

Many thanks

**Comment by LucasJavaudin** [comment]
The problem was related to the new travelers' paths file. It should now be fixed. Sorry for the trouble.
