### ISSUE TITLE
File Importation issue

### ISSUE THREAD

**Issue by FilippoAmadio** [LucasJavaudin/MetropolisWebInterface#2]
Hello,
I have a problem in the file importation procedure. I tried to import a file for "zones" (simulation Circular City) but I do not manage it. The file is in .tsv format and the headers should be ok. I would be pleased if you can help me, I am sure it is something trivial. Thanks in advance.
Filippo
[metropolis ex.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3043838/metropolis.ex.txt)

**Comment by LucasJavaudin** [comment]
There are two problems: (i) you have white-spaces in you header (before _x_ and _y_) and (ii) you must use dots and not commas to separate the decimal part of the coordinates.
Let me know if this does not fix the issue. Hopefully, we will soon implement csv import which would be a little bit easier.
