### ISSUE TITLE
Run Issue

### ISSUE THREAD

**Issue by FilippoAmadio** [LucasJavaudin/MetropolisWebInterface#4]
Hello, 
When I run my simulation the program stops saying :"MetroError:Cannot disaggregate demand. Check inequalities". I cannot figure out my mistake, I hope you can help me.
As usual you can find attached all the files useful for the network.
[metropolis_zone.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3085643/metropolis_zone.txt)
[metropolis_intersection.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3085644/metropolis_intersection.txt)
[metropolis_link.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3085645/metropolis_link.txt)
[metropolis_traveler.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3085646/metropolis_traveler.txt)
[metropolis_PTS.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3085647/metropolis_PTS.txt)

Best,

Filippo

**Comment by LucasJavaudin** [comment]
Hi Filippo,

This error occurs when a traveler's parameters do not respect some constraints. In particular, the desired arrival time must not be lower than the beginning of the recording period.
For your simulation, the desired arrival time is between 8:10 and 9:50 but the start of the recording period is 11:45 (so you should definitely increase the length of the period).

Thank you for your feedback, I will add an explanation for this error in the FAQ.

**Comment by LucasJavaudin** [comment]
Commit f6d741c9c5839f0c80727fe0624e9de49ee2b05a updates the FAQ with a description of this error (and another one).
