### ISSUE TITLE
Runs failed to end

### ISSUE THREAD

**Issue by chaumanfung** [LucasJavaudin/MetropolisWebInterface#5]
Hello, 
I have a few runs that went normally until the stopping criterion was fulfilled, but then the run got stuck from there, e.g. 
Tue Apr 16 16:09:53 2019:Saving results...
Tue Apr 16 16:09:53 2019:Ending simulation normally
Tue Apr 16 16:09:53 2019:Elapsed:0D4H35M22S
Tue Apr 16 16:09:53 2019:Performance:0D0H5M30S per iteration
(all normal, then from here the run just didn't produce the disaggregate results and got stuck as "current run")
It happened in Run 4 (and 5) of my Brussels2 simulation, and also in some runs of my private Brussels simulation.  
Any advice? 
Thanks in advance!

**Comment by LucasJavaudin** [comment]
I think that the run ended correctly but Metrosim was not able to close the database, and thus the ending script never started.

It is very likely that the issue is related to #7.

**Comment by chaumanfung** [comment]
I think I have a run that is not able to close at the moment.
And the common point as the last time it happened: I tried with a large list of tolls...

**Comment by LucasJavaudin** [comment]
I think that the ending script was never triggered because I updated the website this afternoon. I manually ran the script, the problem is solved (for this run at least).
I will try to make sure that this does not happen anymore.

**Comment by chaumanfung** [comment]
It looks like it's happening again:
_Fri May 3 18:46:01 2019:Ending simulation normally
Fri May 3 18:46:01 2019:Elapsed:0D4H15M29S
Fri May 3 18:46:01 2019:Performance:0D0H5M6S per iteration_
But it is still in progress at the moment.

**Comment by LucasJavaudin** [comment]
Sorry about that. I think that the run is so long that, by the time it ends, the server restarted and thus "forgot" to run the ending script.
If this is the problem, it will be fixed when the queuing system is done.

**Comment by LucasJavaudin** [comment]
Commit f34867ced82f6aab1b819d6c1a2132d28356d054 improves the verbosity of the ending script to make sure that the issue happen because the script is never triggered (and not because the script runs and crashes).

**Comment by chaumanfung** [comment]
Thanks! so the queuing system will solve the problem. But in the meantime:
_Mon May 6 17:57:53 2019:Ending simulation normally
Mon May 6 17:57:53 2019:Elapsed:0D2H9M38S
Mon May 6 17:57:53 2019:Performance:0D0H6M28S per iteration_
I think I have the same problem again...

**Comment by LucasJavaudin** [comment]
So something strange is happening with the ending script. I will probably be able to figure out what is the problem the next time it happens.

**Comment by LucasJavaudin** [comment]
It happened again and, very surprisingly, the issue is related to the matplotlib import. I updated the website with a fix (or at least I think it is a fix).

**Comment by chaumanfung** [comment]
I have not had the same problem since this fix. I guess this is the real fix. Thanks a lot for all the work!
