### ISSUE TITLE
"Gateway Timeout" 

### ISSUE THREAD

**Issue by chaumanfung** [LucasJavaudin/MetropolisWebInterface#6]
Hello,

I have this "The gateway did not receive a timely response from the upstream server or application." for a few times when I tried to (a)  copy a pretty big simulation (e.g. Brussels2) , or (b) import or even delete the big list of time varying tolls (there could be many zeros, but I still create one row for each link and always have 15 (or 20) mins as time interval for each link, for my convenience...). 

So my question is: are there ways that I can avoid this "error"? Or the best way is just to break up the toll file (>10000 rows, around 15-20 time intervals) every time I import them?

Any suggestions? Thanks in advance!

(an example of the toll file attached)
[tolls2.txt](https://github.com/LucasJavaudin/MetropolisWebInterface/files/3088561/tolls2.txt)

**Comment by LucasJavaudin** [comment]
I restarted the MySQL server of the website, does it work now? Does it work if you try to import a smaller file?

This issue is probably related to #7 (the MySQL server was very busy because of the running simulations so it probably could not make any change to the database).

**Comment by chaumanfung** [comment]
Thanks! I have the copy of the simulation now. (But when I tried to make another copy, just for the sake of trying, the "gateway timeout" message showed again.)

I'll experiment more on toll imports these couple of days and see how it goes.

**Comment by chaumanfung** [comment]
some update: I tried importing a toll scheme with ~6000 rows (in Toll schemes Brussels2) just now. The same "gateway timeout" message was shown but I can see that part of the file was imported. But the weird thing is when I tried to "reset tolls", not all the tolls are removed. I ended up pressing the reset toll button multiple times and "there are xx links with a toll" on the pricing page and "there are yy policies" on the simulation page kept changing when I moved back and forth (but xx!=yy)...

**Comment by LucasJavaudin** [comment]
The _Gateway Timeout_ error occurs when the server is not able to respond in time. Because a simulation copy can take up to two hours, this error can occur but the server is still copying the simulation in the background. For now, the only think that you can do is to take a coffee break while performing such large operations.

Concerning your last comment, I think that when you got the error, the server was still importing the file in the background. Hence, when you tried to delete the tolls, it did not delete the tolls which were not imported yet.

**Comment by chaumanfung** [comment]
I see. So it's better that I let the large operations (copying or importing) continue in the background when I get this _Gateway Timeout_ error, instead of trying to reset and start over.
Thanks!

**Comment by LucasJavaudin** [comment]
Yes indeed. 

Our top priorities for the website is a queuing system to manage this kind of background tasks efficiently.
