### ISSUE TITLE
disaggregated results for large network

### ISSUE THREAD

**Issue by chaumanfung** [LucasJavaudin/MetropolisWebInterface#8]
(not sure this is really an issue but it might be of interest for other users...)

Currently for large networks, only historical incoming flows are available as a tsv file.
I just wonder if it is possible to access the outgoing flows and travel times for all the links for a large network? Is it because that it will take too long to write all these on the tsv file? If so, is it possible to access it via any other ways?

This is useful and relevant for me because I am working on some scripts to find optimal tolls. But I'm pretty new to all these, so what I do is:  importing the output tsv, do the calculations, write the calculated tolls on a tsv for import in metropolis, and continue.

Thanks in advance!

**Comment by LucasJavaudin** [comment]
My concern was that the file would be too big and hence could not be sent to the user. I just updated the server to commit b532b936dbb00f2262ebb2f270b55db477ecf9af which increases the link threshold for a network to be considered as "large". Let us know whether it works. (Note that it will not affect the runs currently in progress.)

By the way, do you prefer the current version with the incoming flows, outgoing flows and travel times in the same file or would you rather have 6 different files (for historical and simulated values) ? (Splitting the file could be a solution if the server cannot send very large files.)

**Comment by chaumanfung** [comment]
Thanks a lot for the work and the update! I'll try.

I think in my case having 6 different files will not make a big difference, because I get the files using "requests", then read them and do calculations (pandas). So I guess having 6 files won't have too much effect on speed or convenience, at least in my case.
