### ISSUE TITLE
Events and articles are added multiple times

### ISSUE THREAD

**Issue by LucasJavaudin** [LucasJavaudin/MetropolisWebInterface#9]
If I add an event or an article, I am redirected to the events/articles page but if I refresh the page, the event/article is added a second time.
I think that this issue will be fixed if the user is redirected with HttpResponseRedirect.

**Comment by syrix78** [comment]
Issue should now be fixed with commit [79a785e ](https://github.com/LucasJavaudin/MetropolisWebInterface/commit/79a785e7553fd7318175a7fd305ea4044ac1b130)on master branch
